#Basic If-Else Statements:

###1. Write a Python program to check if a given number is positive or negative.

In [ ]:
num = float(input("Enter a number: "))

if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

Enter a number: 4
The number is positive.


###2. Create a program that determines if a person is eligible to vote based on their age.

In [ ]:
age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

Enter your age: 25
You are eligible to vote.


###3. Develop a program to find the maximum of two numbers using if-else statements.

In [ ]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

if num1 > num2:
    print("The maximum is", num1)
else:
    print("The maximum is", num2)

Enter the first number: 12
Enter the second number: 12
The maximum is 12.0


###4. Write a Python script to classify a given year as a leap year or not.

In [ ]:
year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year, "is a leap year.")
else:
    print(year, "is not a leap year.")

Enter a year: 2023
2023 is not a leap year.


###5. Create a program that checks whether a character is a vowel or a consonant.

In [ ]:
char = input("Enter a character: ")

if char in "aeiouAEIOU":
    print(char, "is a vowel.")
else:
    print(char, "is a consonant.")

Enter a character: c
c is a consonant.


###6. Implement a program to determine whether a given number is even or odd.

In [ ]:
num = int(input("Enter the number to check odd or even: "))

if num % 2 == 0:
  print("The number", num, "is even")
elif num % 2 != 0 :
  print("The number", num, "is odd")
else :
  print("The number is valid")

Enter the number to check odd or even: 12
The number 12 is even


###7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.

In [ ]:
num = float(input("Enter a number: "))

if num < 0:
    abs_value = -num
else:
    abs_value = num

print("The absolute value is", abs_value)

Enter a number: 25
The absolute value is 25.0


###8. Develop a program that determines the largest of three given numbers using if-else statements.

In [ ]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

if num1 >= num2 and num1 >= num3:
    largest = num1
elif num2 >= num1 and num2 >= num3:
    largest = num2
else:
    largest = num3

print("The largest number is", largest)

Enter the first number: 12
Enter the second number: 47
Enter the third number: 36
The largest number is 47.0


###9. Create a program that checks if a given string is a palindrome.

In [ ]:
string = input("Enter a string: ")

# Remove spaces and convert to lowercase for case-insensitive comparison
string = string.replace(" ", "").lower()

if string == string[::-1]:
    print("It's a palindrome.")
else:
    print("It's not a palindrome.")

Enter a string: fkugf
It's not a palindrome.


###10. Write a Python program to calculate the grade based on a student's score.

In [ ]:
score = float(input("Enter the student's score: "))

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
elif score >= 60:
    grade = "D"
else:
    grade = "F"

print("The student's grade is:", grade)

Enter the student's score: 65
The student's grade is: D


#Nested If-Else Statements:

###12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.

In [ ]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

if num1 >= num2:
    if num1 >= num3:
        largest = num1
    else:
        largest = num3
else:
    if num2 >= num3:
        largest = num2
    else:
        largest = num3

print("The largest number is", largest)

Enter the first number: 15
Enter the second number: 12
Enter the third number: 35
The largest number is 35.0


###13. Develop a program that checks if a year is a leap year and also if it is a century year.

In [ ]:
year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year, "is a leap year.")

    if year % 100 == 0:
        print(year, "is a century year.")
else:
    print(year, "is not a leap year.")

Enter a year: 2022
2022 is not a leap year.


###14. Write a Python script to determine if a number is positive, negative, or zero.

In [ ]:
num = float(input("Enter a number: "))

if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

Enter a number: 15
The number is positive.


###15. Create a program to check if a person is a teenager (between 13 and 19 years old).

In [ ]:
age = int(input("Enter the person's age: "))

if 13 <= age <= 19:
    print("The person is a teenager.")
else:
    print("The person is not a teenager.")

Enter the person's age: 12
The person is not a teenager.


###16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).

In [ ]:
angle = float(input("Enter the angle in degrees: "))

if angle < 90:
    print("It's an acute angle.")
elif angle == 90:
    print("It's a right angle.")
else:
    print("It's an obtuse angle.")

Enter the angle in degrees: 49
It's an acute angle.


###17. Write a Python program to calculate the roots of a quadratic equation.

In [ ]:
import math

a = float(input("Enter the coefficient 'a': "))
b = float(input("Enter the coefficient 'b': "))
c = float(input("Enter the coefficient 'c': "))

discriminant = b**2 - 4*a*c

if discriminant > 0:
    root1 = (-b + math.sqrt(discriminant)) / (2*a)
    root2 = (-b - math.sqrt(discriminant)) / (2*a)
    print("Two real and distinct roots: Root1 =", root1, "Root2 =", root2)
elif discriminant == 0:
    root1 = -b / (2*a)
    print("One real root: Root1 =", root1)
else:
    realPart = -b / (2*a)
    imaginaryPart = math.sqrt(-discriminant) / (2*a)
    print("Two complex roots: Root1 =", realPart, "+", imaginaryPart, "i and Root2 =", realPart, "-", imaginaryPart, "i")

###18. Determine the day of the week

In [ ]:
day_number = int(input("Enter a number (1 for Monday, 2 for Tuesday, etc.): "))

days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

if 1 <= day_number <= 7:
    print("It's", days[day_number - 1])
else:
    print("Invalid input.")

Enter a number (1 for Monday, 2 for Tuesday, etc.): 5
It's Friday


###19. Check for leap year and divisible by 400

In [ ]:
year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year, "is a leap year.")

    if year % 400 == 0:
        print(year, "is evenly divisible by 400.")
else:
    print(year, "is not a leap year.")

Enter a year: 2019
2019 is not a leap year.


###20. Check if a number is prime

In [ ]:
num = int(input("Enter a number: "))

if num <= 1:
    print("Not a prime number")
else:
    is_prime = True
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print("It's a prime number.")
    else:
        print("Not a prime number.")

Enter a number: 24
Not a prime number.


#Elif Statements:

###21. Write a Python program to assign grades based on different ranges of scores using elif statements.


In [ ]:
score = float(input("Enter the student's score: "))

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
elif score >= 60:
    grade = "D"
else:
    grade = "F"

print("The student's grade is:", grade)

Enter the student's score: 65
The student's grade is: D


###22. Implement a program to determine the type of a triangle based on its angles.

In [ ]:
angle1 = int(input("Enter the first angle: "))
angle2 = int(input("Enter the second angle: "))
angle3 = int(input("Enter the third angle: "))

if angle1 == 90 or angle2 == 90 or angle3 == 90:
    print("It's a right triangle.")
elif angle1 < 90 and angle2 < 90 and angle3 < 90:
    print("It's an acute triangle.")
else:
    print("It's an obtuse triangle.")

Enter the first angle: 24
Enter the second angle: 23
Enter the third angle: 12
It's an acute triangle.


###23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using elif statements.

In [ ]:
weight = float(input("Enter the person's weight (in kg): "))
height = float(input("Enter the person's height (in meters): "))

bmi = weight / (height ** 2)

if bmi < 18.5:
    category = "Underweight"
elif 18.5 <= bmi < 24.9:
    category = "Normal"
elif 25 <= bmi < 29.9:
    category = "Overweight"
else:
    category = "Obese"

print("The person's BMI category is:", category)

Enter the person's weight (in kg): 95
Enter the person's height (in meters): 12
The person's BMI category is: Underweight


###24. Create a program that determines whether a given number is positive, negative, or zero using elif statements.

In [ ]:
num = float(input("Enter a number: "))

if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

Enter a number: 65
The number is positive.


###25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif statements.

In [ ]:
char = input("Enter a character: ")

if char.isalpha():
    if char.islower():
        print("It's a lowercase letter.")
    else:
        print("It's an uppercase letter.")
else:
    print("It's a special character.")

Enter a character: njdcna
It's a lowercase letter.


###26. Implement a program to calculate the discounted price based on different purchase amounts using elif statements.

In [ ]:
purchase_amount = float(input("Enter the purchase amount: "))

if purchase_amount < 50:
    discount = 0
elif purchase_amount < 100:
    discount = 10
elif purchase_amount < 200:
    discount = 20
else:
    discount = 30

discounted_price = purchase_amount - (purchase_amount * discount / 100)
print("Discounted price: $", discounted_price)

Enter the purchase amount: 45
Discounted price: $ 45.0


###27. Develop a program to calculate the electricity bill based on different consumption slabs using elif statements.

In [ ]:
units_consumed = int(input("Enter the number of units consumed: "))

if units_consumed <= 100:
    bill = units_consumed * 1.5
elif units_consumed <= 200:
    bill = 100 * 1.5 + (units_consumed - 100) * 2.0
else:
    bill = 100 * 1.5 + 100 * 2.0 + (units_consumed - 200) * 3.0

print("Electricity bill: $", bill)

Enter the number of units consumed: 57
Electricity bill: $ 85.5


###28. Create a program to determine the type of quadrilateral based on its angles and sides using elif statements.

In [ ]:
num_sides = int(input("Enter the number of sides of the quadrilateral: "))
angle_sum = int(input("Enter the sum of interior angles: "))

if num_sides == 4:
    if angle_sum == 360:
        print("It's a quadrilateral.")
    elif angle_sum == 360 and all(int(input(f"Enter the measure of angle {i+1}: ")) == 90 for i in range(4)):
        print("It's a rectangle.")
    elif all(int(input(f"Enter the measure of angle {i+1}: ")) < 90 for i in range(4)):
        print("It's a rhombus.")
    else:
        print("It's a generic quadrilateral.")
else:
    print("Not a quadrilateral.")

Enter the number of sides of the quadrilateral: 42
Enter the sum of interior angles: 32
Not a quadrilateral.


###29. Write a Python script to determine the season based on a user-provided month using elif statements.

In [ ]:
month = int(input("Enter the month (1-12): "))

if 3 <= month <= 5:
    season = "Spring"
elif 6 <= month <= 8:
    season = "Summer"
elif 9 <= month <= 11:
    season = "Autumn"
else:
    season = "Winter"

print("The season is", season)

Enter the month (1-12): 54
The season is Winter


###30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using elif statements.

In [ ]:
year = int(input("Enter the year: "))
month = int(input("Enter the month (1-12): "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    is_leap_year = True
else:
    is_leap_year = False

if month in {4, 6, 9, 11}:
    days_in_month = 30
elif month == 2:
    if is_leap_year:
        days_in_month = 29
    else:
        days_in_month = 28
else:
    days_in_month = 31

if is_leap_year:
    print("It's a leap year.")
else:
    print("It's a common year.")
print("The month has", days_in_month, "days.")

Enter the year: 2017
Enter the month (1-12): 4
It's a common year.
The month has 30 days.


#Basic Level:

###1. Write a Python program that checks if a given number is positive, negative, or zero.

In [ ]:
n = float(input("Enter the number: "))

if n > 0 :
  print("The given number {} is positive".format(n))
elif n < 0 :
  print("The given number {} is negative".format(n))
else :
  print("The given number {} is zero".format(n))

Enter the number: 0
The given number 0 is zero


###2. Create a program to determine if a person is eligible to vote based on their age.

In [ ]:
age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")


Enter your age: 26
You are eligible to vote.


###3. Write a program to find the maximum of two given numbers using conditional statements.

In [ ]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

if num1 > num2:
    print("The maximum is", num1)
else:
    print("The maximum is", num2)

Enter the first number: 12
Enter the second number: 32
The maximum is 32.0


###4. Develop a program that calculates the grade of a student based on their exam score.

In [ ]:
score = float(input("Enter the exam score: "))

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
elif score >= 60:
    grade = "D"
else:
    grade = "F"

print("The grade is", grade)

Enter the exam score: 95
The grade is A


###5. Create a program that checks if a year is a leap year or not.

In [ ]:
year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print("Leap year")
else:
    print("Not a leap year")

Enter a year: 2026
Not a leap year


###6. Write a program to classify a triangle based on its sides' lengths.

In [ ]:
a = float(input("Enter the length of side A: "))
b = float(input("Enter the length of side B: "))
c = float(input("Enter the length of side C: "))

if a == b == c:
    print("Equilateral triangle")
elif a == b or b == c or a == c:
    print("Isosceles triangle")
else:
    print("Scalene triangle")

Enter the length of side A: 12
Enter the length of side B: 25
Enter the length of side C: 9
Scalene triangle


###7. Build a program that determines the largest of three given numbers.

In [ ]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

max_num = max(num1, num2, num3)
print("The largest number is", max_num)

Enter the first number: 12
Enter the second number: 32
Enter the third number: 65
The largest number is 65.0


###8. Develop a program that checks whether a character is a vowel or a consonant.

In [ ]:
char = input("Enter a character: ")

if char in 'aeiouAEIOU':
    print("Vowel")
else:
    print("Consonant")

Enter a character: f
Consonant


###9. Create a program to calculate the total cost of a shopping cart based on discounts.

In [ ]:
total_cost = 0

while True:
    item = input("Enter the item name (or 'done' to finish): ")
    if item == 'done':
        break
    price = float(input("Enter the price: "))
    quantity = float(input("Enter the quantity: "))
    total_cost += price * quantity

print("Total cost: $", total_cost)

Enter the item name (or 'done' to finish): good
Enter the price: 354
Enter the quantity: 7
Enter the item name (or 'done' to finish): nice
Enter the price: 652
Enter the quantity: 12
Enter the item name (or 'done' to finish): ksd
Enter the price: 45
Enter the quantity: 1.5
Enter the item name (or 'done' to finish): done
Total cost: $ 10369.5


###10. Write a program that checks if a given number is even or odd.

In [ ]:
number = int(input("Enter a number: "))

if number % 2 == 0:
    print("Even")
else:
    print("Odd")

Enter a number: 12
Even


#Intermediate Level:

###11. Write a program that calculates the roots of a quadratic equation .

In [ ]:
import math

# Input coefficients
a = float(input("Enter the coefficient a: "))
b = float(input("Enter the coefficient b: "))
c = float(input("Enter the coefficient c: "))

# Calculate the discriminant
D = b**2 - 4*a*c

# Check the nature of the roots
if D > 0:
    # Two distinct real roots
    x1 = (-b + math.sqrt(D)) / (2*a)
    x2 = (-b - math.sqrt(D)) / (2*a)
    print(f"The roots are real and distinct: x1 = {x1}, x2 = {x2}")
elif D == 0:
    # One real root
    x1 = -b / (2*a)
    print(f"The root is real and repeated: x1 = {x1}")
else:
    # Two complex roots
    real_part = -b / (2*a)
    imaginary_part = math.sqrt(abs(D)) / (2*a)
    print(f"The roots are complex: x1 = {real_part} + {imaginary_part}i, x2 = {real_part} - {imaginary_part}i")


Enter the coefficient a: 2
Enter the coefficient b: 3
Enter the coefficient c: 9
The roots are complex: x1 = -0.75 + 1.984313483298443i, x2 = -0.75 - 1.984313483298443i


###12. Create a program that determines the day of the week based on the day number (1-7).

In [ ]:
day_number = int(input("Enter a day number (1-7): "))

if 1 <= day_number <= 7:
    days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    print("The day is", days[day_number - 1])
else:
    print("Invalid day number.")

Enter a day number (1-7): 6
The day is Saturday


###13. Develop a program that calculates the factorial of a given number using recursion.

In [ ]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

num = int(input("Enter a number: "))
result = factorial(num)
print("Factorial:", result)

Enter a number: 25
Factorial: 15511210043330985984000000


###14. Write a program to find the largest among three numbers without using the `max()` function.

In [ ]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

if num1 >= num2 and num1 >= num3:
    largest = num1
elif num2 >= num1 and num2 >= num3:
    largest = num2
else:
    largest = num3

print("The largest number is", largest)

Enter the first number: 25
Enter the second number: 34
Enter the third number: 75
The largest number is 75.0


###15. Create a program that simulates a basic ATM transaction menu.

In [1]:
balance = 1000  # Initial balance

while True:
    print("ATM Menu:")
    print("1. Check Balance")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        print("Balance: $", balance)
    elif choice == 2:
        deposit = float(input("Enter the deposit amount: "))
        balance += deposit
        print("Deposited $", deposit)
    elif choice == 3:
        withdraw = float(input("Enter the withdrawal amount: "))
        if withdraw > balance:
            print("Insufficient funds")
        else:
            balance -= withdraw
            print("Withdrawn $", withdraw)
    elif choice == 4:
        break
    else:
        print("Invalid choice. Please select a valid option.")


ATM Menu:
1. Check Balance
2. Deposit
3. Withdraw
4. Exit
Enter your choice: 3
Enter the withdrawal amount: 2000
Insufficient funds
ATM Menu:
1. Check Balance
2. Deposit
3. Withdraw
4. Exit
Enter your choice: 2
Enter the deposit amount: 2000
Deposited $ 2000.0
ATM Menu:
1. Check Balance
2. Deposit
3. Withdraw
4. Exit
Enter your choice: 1
Balance: $ 3000.0
ATM Menu:
1. Check Balance
2. Deposit
3. Withdraw
4. Exit
Enter your choice: 4


###16. Build a program that checks if a given string is a palindrome or not.

In [2]:
def is_palindrome(s):
    s = s.lower().replace(" ", "")  # Convert to lowercase and remove spaces
    return s == s[::-1]

text = input("Enter a string: ")
if is_palindrome(text):
    print("It's a palindrome.")
else:
    print("It's not a palindrome.")


Enter a string: tenet
It's a palindrome.


###17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.

In [4]:
numbers = [float(x) for x in input("Enter a list of numbers separated by spaces: ").split()]
if len(numbers) < 3:
    print("At least 3 numbers are required.")
else:
    numbers.sort()
    trimmed_numbers = numbers[1:-1]  # Exclude the smallest and largest values
    average = sum(trimmed_numbers) / len(trimmed_numbers)
    print("Average (excluding min and max):", average)


Enter a list of numbers separated by spaces: 2 3 4 6 1 8 9
Average (excluding min and max): 4.6


###18. Develop a program that converts a given temperature from Celsius to Fahrenheit.

In [5]:
celsius = float(input("Enter the temperature in Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print("Temperature in Fahrenheit:", fahrenheit)

Enter the temperature in Celsius: 45
Temperature in Fahrenheit: 113.0


###19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.

In [6]:
while True:
    print("Calculator Menu:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 5:
        break

    num1 = float(input("Enter the first number: "))
    num2 = float(input("Enter the second number: "))

    if choice == 1:
        result = num1 + num2
    elif choice == 2:
        result = num1 - num2
    elif choice == 3:
        result = num1 * num2
    elif choice == 4:
        if num2 == 0:
            print("Division by zero is not allowed.")
            continue
        result = num1 / num2
    else:
        print("Invalid choice. Please select a valid option.")
        continue

    print("Result:", result)

Calculator Menu:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Exit
Enter your choice: 3
Enter the first number: 45
Enter the second number: 5
Result: 225.0
Calculator Menu:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Exit
Enter your choice: 2
Enter the first number: 495
Enter the second number: 324
Result: 171.0
Calculator Menu:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Exit
Enter your choice: 5


###20. Write a program that determines the roots of a cubic equation using the Cardano formula.

In [9]:
import math

# Coefficients of the cubic equation: ax^3 + bx^2 + cx + d = 0
a = float(input("Enter the coefficient a: "))
b = float(input("Enter the coefficient b: "))
c = float(input("Enter the coefficient c: "))
d = float(input("Enter the coefficient d: "))

# Calculate some intermediate values
delta0 = b**2 - 3*a*c
delta1 = 2*b**3 - 9*a*b*c + 27*a**2*d
C = ((delta1 + math.sqrt(delta1**2 - 4*delta0**3)) / 2)**(1/3)

# Calculate the roots
root1 = -(1 / (3*a)) * (b + C + delta0 / C)
root2 = -(1 / (3*a)) * (b + C * complex(-0.5, math.sqrt(3) / 2) + delta0 / (C * complex(-0.5, math.sqrt(3) / 2)))
root3 = -(1 / (3*a)) * (b + C * complex(-0.5, -math.sqrt(3) / 2) + delta0 / (C * complex(-0.5, -math.sqrt(3) / 2)))

print("Real root:", root1.real)
print("Complex roots:", root2, root3)

Enter the coefficient a: 3
Enter the coefficient b: 15
Enter the coefficient c: 12
Enter the coefficient d: 32
Real root: -4.6335531530789975
Complex roots: (-0.18322342346050105-1.5061468169168455j) (-0.18322342346050105+1.5061468169168455j)


#Advanced Level:

###21. Create a program that calculates the income tax based on the user's income and tax brackets.

In [11]:
income = float(input("enter your income"))

if income <= 10000:
    tax = 0.05 * income
elif income <= 50000:
    tax = 500 + 0.1 * (income - 10000)
else:
    tax = 5000 + 0.2 * (income - 50000)

print("Income tax: $", tax)

enter your income50000
Income tax: $ 4500.0


###22. Write a program that simulates a rock-paper-scissors game against the computer.

In [13]:
import random

choices = ["rock", "paper", "scissors"]
computer_choice = random.choice(choices)

user_choice = input("Enter your choice (rock, paper, scissors): ")

print("Computer chose:", computer_choice)
print("You chose:", user_choice)

if user_choice == computer_choice:
    print("It's a tie!")
elif (
    (user_choice == "rock" and computer_choice == "scissors") or
    (user_choice == "paper" and computer_choice == "rock") or
    (user_choice == "scissors" and computer_choice == "paper")
):
    print("You win!")
else:
    print("Computer wins!")

Enter your choice (rock, paper, scissors): rock
Computer chose: rock
You chose: rock
It's a tie!


###23. Develop a program that generates a random password based on user preferences (length, complexity).

In [3]:
import random
import string

length = int(input("Enter the password length: "))
complexity = input("Enter complexity (easy, medium, hard): ")

if complexity == "easy":
    characters = string.ascii_letters
elif complexity == "medium":
    characters = string.ascii_letters + string.digits
elif complexity == "hard":
    characters = string.ascii_letters + string.digits + string.punctuation
else:
    print("Invalid complexity level.")
    exit()

password = ''.join(random.choice(characters) for _ in range(length))
print("Generated password:", password)


Enter the password length: 10
Enter complexity (easy, medium, hard): hard
Generated password: u."{.HoX=X


###24. Create a program that implements a simple text-based adventure game with branching scenarios.

In [4]:
print("You find yourself in a forest. There are two paths ahead.")
choice = input("Do you take the left path or the right path? (left/right): ")

if choice == "left":
    print("You encounter a river. Do you swim across or find a bridge?")
    choice = input("Swim or bridge? (swim/bridge): ")

    if choice == "swim":
        print("You made it across the river safely.")
    elif choice == "bridge":
        print("You find a bridge and safely cross the river.")
    else:
        print("Invalid choice. You're lost in the forest.")
else:
    print("You come across a hidden treasure chest. You win the game!")

You find yourself in a forest. There are two paths ahead.
Do you take the left path or the right path? (left/right): left
You encounter a river. Do you swim across or find a bridge?
Swim or bridge? (swim/bridge): swim
You made it across the river safely.


###25. Build a program that solves a linear equation for x, considering different cases.

In [5]:
# Linear equation: ax + b = 0
a = float(input("Enter the coefficient 'a': "))
b = float(input("Enter the coefficient 'b': "))

if a == 0:
    if b == 0:
        print("Infinite solutions (0x = 0)")
    else:
        print("No solution (0x = b, where b is not 0)")
else:
    x = -b / a
    print("Solution: x =", x)


Enter the coefficient 'a': 12
Enter the coefficient 'b': 6
Solution: x = -0.5


###26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.

In [7]:
quiz = [
    {
        "question": "What is the capital of France?",
        "options": ["Paris", "London", "Berlin"],
        "correct_answer": "Paris"
    },
    {
        "question": "Which planet is known as the Red Planet?",
        "options": ["Earth", "Mars", "Venus"],
        "correct_answer": "Mars"
    },
    {
        "question": "What is the largest mammal on Earth?",
        "options": ["Giraffe", "Elephant", "Blue Whale"],
        "correct_answer": "Blue Whale"
    }
]

score = 0

for question in quiz:
    print(question["question"])
    for i, option in enumerate(question["options"], start=1):
        print(f"{i}. {option}")

    user_answer = int(input("Enter the number of your answer: "))
    if question["options"][user_answer - 1] == question["correct_answer"]:
        print("Correct!\n")
        score += 1
    else:
        print(f"Wrong. The correct answer is {question['correct_answer']}\n")

print(f"Your score: {score}/{len(quiz)}")


What is the capital of France?
1. Paris
2. London
3. Berlin
Enter the number of your answer: 1
Correct!

Which planet is known as the Red Planet?
1. Earth
2. Mars
3. Venus
Enter the number of your answer: 3
Wrong. The correct answer is Mars

What is the largest mammal on Earth?
1. Giraffe
2. Elephant
3. Blue Whale
Enter the number of your answer: 3
Correct!

Your score: 2/3


###27. Develop a program that determines whether a given year is a prime number or not.

In [8]:
year = int(input("Enter a year: "))

if year > 1:
    for i in range(2, year):
        if (year % i) == 0:
            print("Not a prime year")
            break
    else:
        print("Prime year")
else:
    print("Not a prime year")

Enter a year: 2023
Not a prime year


###28. Create a program that sorts three numbers in ascending order using conditional statements.

In [9]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

if num1 <= num2 and num1 <= num3:
    smallest = num1
    if num2 <= num3:
        middle = num2
        largest = num3
    else:
        middle = num3
        largest = num2
elif num2 <= num1 and num2 <= num3:
    smallest = num2
    if num1 <= num3:
        middle = num1
        largest = num3
    else:
        middle = num3
        largest = num1
else:
    smallest = num3
    if num1 <= num2:
        middle = num1
        largest = num2
    else:
        middle = num2
        largest = num1

print("Sorted numbers in ascending order:", smallest, middle, largest)


Enter the first number: 65
Enter the second number: 48
Enter the third number: 98
Sorted numbers in ascending order: 48.0 65.0 98.0


###30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based


In [18]:
weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))

bmi = weight / (height ** 2)
print("Your BMI is:", bmi)

if bmi < 18.5:
    print("Underweight")
    print("Recommendation: Consider gaining some weight.")
elif 18.5 <= bmi < 24.9:
    print("Normal weight")
    print("Recommendation: Maintain a healthy lifestyle.")
elif 24.9 <= bmi < 29.9:
    print("Overweight")
    print("Recommendation: Consider losing some weight.")
else:
    print("Obese")
    print("Recommendation: Consult a healthcare professional for guidance.")


Enter your weight in kilograms: 12
Enter your height in meters: 3
Your BMI is: 1.3333333333333333
Underweight
Recommendation: Consider gaining some weight.


#Challenge Level:

###31. Create a program that validates a password based on complexity rules (length, characters, etc.).

In [19]:
import re

def is_valid_password(password):
    # Check if the password is at least 8 characters long
    if len(password) < 8:
        return False

    # Check if the password contains at least one uppercase letter
    if not re.search(r'[A-Z]', password):
        return False

    # Check if the password contains at least one lowercase letter
    if not re.search(r'[a-z]', password):
        return False

    # Check if the password contains at least one digit
    if not re.search(r'[0-9]', password):
        return False

    # Check if the password contains at least one special character
    if not re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
        return False

    return True

password = input("Enter a password: ")

if is_valid_password(password):
    print("Valid password")
else:
    print("Invalid password")

Enter a password: najbsd
Invalid password


###32. Develop a program that performs matrix addition and subtraction based on user input.

In [22]:
import numpy as np

# Input matrix A
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

A = []
for i in range(rows):
    row = [int(x) for x in input(f"Enter values for row {i + 1} (separated by spaces): ").split()]
    A.append(row)

# Input matrix B
B = []
for i in range(rows):
    row = [int(x) for x in input(f"Enter values for row {i + 1} of matrix B (separated by spaces): ").split()]
    B.append(row)

# Matrix addition
result_addition = np.add(A, B)

# Matrix subtraction
result_subtraction = np.subtract(A, B)

print("Matrix A:")
print(np.array(A))

print("Matrix B:")
print(np.array(B))

print("Matrix A + Matrix B:")
print(result_addition)

print("Matrix A - Matrix B:")
print(result_subtraction)

Enter the number of rows: 2
Enter the number of columns: 3
Enter values for row 1 (separated by spaces): 2 3 5
Enter values for row 2 (separated by spaces): 2 3 0
Enter values for row 1 of matrix B (separated by spaces): 1 6 8
Enter values for row 2 of matrix B (separated by spaces): 5 4 3
Matrix A:
[[2 3 5]
 [2 3 0]]
Matrix B:
[[1 6 8]
 [5 4 3]]
Matrix A + Matrix B:
[[ 3  9 13]
 [ 7  7  3]]
Matrix A - Matrix B:
[[ 1 -3 -3]
 [-3 -1 -3]]


###33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean algorithm.

In [23]:
def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

result = gcd(num1, num2)
print("GCD:", result)

Enter the first number: 23
Enter the second number: 22
GCD: 1
